feat: add more credentials
12joan/twitter-client pull request #18
Opened 2023-07-06 15:55 UTC by nickchen120235

Closes #2

This PR introduces all four key pairs found [here](https://git.sr.ht/~cloutier/bird.makeup/tree/master/item/src/BirdsiteLive.Twitter/Tools/TwitterAuthenticationInitializer.cs#L36)

## Testing Instructions
No functionality changes. Things should still work.

2023-07-06 15:58 UTC, 12joan requested changes
Looks good! Just one small typo

2023-07-06 15:58 UTC, 12joan commented on src/twitter.ts
> +  console.log(`Using crednetial: ${client}`)
```suggestion
  console.log(`Using credentials: ${client}`)
```

2023-07-07 02:45 UTC, nickchen120235 commented
I'm converting this to draft temporarily because I found some other tokens that might work. https://github.com/zedeus/nitter/pull/925

I'll be back if any (or none) of them works.

2023-07-07 04:36 UTC, nickchen120235 commented
So both the `developer.twitter.com` and the `ipad` token will return 20 tweets per request. But the `tweetdeck` token usually returns less than 20 tweets.

2023-07-07 07:16 UTC, 12joan commented
That's interesting. I'll let you decide what's best here.

Incidentally, I'm liking Twitter's new tagline, courtesy of DuckDuckGo.
<img width="1014" alt="Search result for TweetDeck. The text under the result is 'Something went wrong, but don't fret — let's give it another shot.'" src="https://github.com/12joan/twitter-client/assets/4272090/ac86de43-c22d-4aff-b8c3-c092956adc02">

2023-07-07 07:46 UTC, nickchen120235 commented
So the options are
1. Keep the `tweetdeck` key, pick the keys randomly
2. 1. but give the `tweetdeck` key a lower weight (I'm thinking 20% for it and 40% for each of the other two keys)
3. 1. but we DO NOT cache the `tweetdeck` key (actually we may not need to cache the bearer key anymore because they are hard-coded)
4. Remove the `tweetdeck` key

2023-07-07 08:18 UTC, 12joan commented
That sounds all right to me. No need to remove guest token caching, since [the cache is keyed on the access token](https://github.com/12joan/twitter-client/blob/main/src/twitter.ts#L141).

2023-07-07 08:19 UTC, 12joan commented
Are we confident that the hardcoded access tokens are just as unlikely to change as the raw client credentials?

2023-07-07 08:33 UTC, nickchen120235 commented
As far as I can tell, the bearer token for the frontend (`twitter.com`) hasn't changed untill all hell breaks loose, so I think it's unlikely to change.

However, considering the Tesla guy is constantly unplugging any means of twitter profile scraping, the tokens may or may not be invalid in the near future.

2023-07-07 15:36 UTC, 12joan commented on src/twitter.ts
> +const fetchAccessToken = (): string => {
Looks good! Might as well rename this to `get[Random]AccessToken` or something like that now that we're not fetching anything.

2023-07-07 16:10 UTC, 12joan approved these changes

2023-07-07 16:10 UTC, 12joan commented
Thanks! Are we ready to merge?

2023-07-07 16:15 UTC, nickchen120235 commented
I think we are good to go!

2023-07-07 16:39 UTC, merged